"""Render the repeated GSQL traversals from the shared relation/window contract."""

from .contract import (
    ASSOCIATIONS,
    WINDOWS,
    AMOUNT_RATIO_WINDOWS,
    AMOUNT_RATIO_FLOOR,
    AMOUNT_RATIO_CAP,
)


def scope_entities(vertex_set: str, label: str) -> str:
    return f"""    IF scope_id != "" THEN
      Scope_{label} = SELECT v FROM {vertex_set}:v -(Entity_In_Training_Scope>:membership)- Temporal_Training_Scope:r
        WHERE r.scope_id == scope_id AND r.ready AND membership.partition >= 1
          AND membership.partition <= visibility_phase
        ACCUM v.@scope_allowed += TRUE;
    END;
"""


def scope_events(vertex_set: str, prefix: str, label: str) -> str:
    return (
        f"""    IF scope_id != "" THEN
      Endpoints_{label} = SELECT a FROM {vertex_set}:t -(({prefix}_From_Account>|{prefix}_To_Account>):role)- Account:a;
"""
        + scope_entities(f"Endpoints_{label}", label)
        + f"""      Blocked_{label} = SELECT t FROM {vertex_set}:t -(({prefix}_From_Account>|{prefix}_To_Account>):role)- Account:a
        WHERE NOT a.@scope_allowed ACCUM t.@scope_blocked += TRUE;
    END;
"""
    )


def render_context_query() -> str:
    # Reusable generated clauses keep field names and windows in one Python contract.
    parts = [
        """USE GRAPH Mule_Pattern_Learner

/* Generated by scripts/temporal/render_training_queries.py. Read-only.
   Each request has independent clocks. Labels and persisted feature caches
   are deliberately absent. Bounded response; adjacency scans are not indexed
   by time and may still be expensive for high-degree entities. */
CREATE OR REPLACE QUERY temporal_training_context(
  LIST<STRING> node_types, LIST<STRING> node_ids,
  LIST<UINT> cutoff_seqs, LIST<UINT> cutoff_times,
  INT per_relation = 2, STRING scope_id = "", INT visibility_phase = 3
) FOR GRAPH Mule_Pattern_Learner SYNTAX V2 {
  TYPEDEF TUPLE<UINT seq, UINT ts, STRING event_id, STRING event_type,
                STRING relation, STRING rail, DOUBLE amount, BOOL amount_present> EventRow;
  TYPEDEF TUPLE<STRING node_type, STRING node_id, STRING relation,
                STRING rail, STRING event_id, UINT event_seq, UINT event_ts_ms,
                DOUBLE amount, BOOL amount_present, UINT age_ms,
                UINT gap_ms, BOOL gap_present, INT pair_count_1h,
                INT pair_count_1d, INT pair_count_7d, UINT peer_first_ms,
                BOOL peer_external, BOOL peer_deposit> MessageRow;
  TYPEDEF TUPLE<UINT seq, STRING node_id, UINT first_ms, BOOL external, BOOL deposit> AssociationRow;
  HeapAccum<EventRow>(8, seq DESC, event_id ASC) @@zelle_out, @@zelle_in,
    @@payment_out, @@payment_in;
  HeapAccum<AssociationRow>(8, seq DESC, node_id ASC) @@association;
  ListAccum<EventRow> @@events;
  ListAccum<MessageRow> @@messages;
  MapAccum<STRING, SumAccum<DOUBLE>> @@features;
  MapAccum<STRING, SetAccum<STRING>> @@distinct;
  MapAccum<STRING, ListAccum<DOUBLE>> @@age_encoding, @@gap_encoding;
  MaxAccum<UINT> @@out_last, @@in_last, @@previous_ts, @@previous_seq;
  SumAccum<INT> @@sender_count, @@recipient_count, @@token_count;
  MaxAccum<STRING> @@sender_id, @@recipient_id, @@token_id;
  SetAccum<VERTEX> @@sender_vertices;
  OrAccum @@invalid;
  OrAccum @scope_allowed, @scope_blocked;
  SumAccum<INT> @@pair_1h, @@pair_1d, @@pair_7d;
  ListAccum<STRING> @@request_types, @@request_ids;
  ListAccum<UINT> @@request_seqs, @@request_times;
  ListAccum<AssociationRow> @@associations;
  MaxAccum<UINT> @@peer_first_ms;
  OrAccum @@peer_external, @@peer_deposit;
  VERTEX root;
  VERTEX event_vertex;
  VERTEX peer_vertex;
  UINT seed_seq = 0;
  UINT seed_ts_ms = 0;
  UINT state_seq = 0;
  UINT age_ms = 0;
  UINT gap_ms = 0;
  DOUBLE incoming_amount = 0.0;
  DOUBLE outgoing_amount = 0.0;
  DOUBLE amount_ratio = 0.0;
  STRING recipient_type = "";
  STRING recipient_id = "";
  STRING peer_type = "";
  STRING peer_id = "";
  STRING event_key = "";
  INT taken = 0;

  @@request_ids = node_ids;
  @@request_types = node_types;
  @@request_seqs = cutoff_seqs;
  @@request_times = cutoff_times;
  IF @@request_ids.size() < 1 OR @@request_ids.size() > 16 OR
     @@request_types.size() != @@request_ids.size() OR @@request_seqs.size() != @@request_ids.size()
     OR @@request_times.size() != @@request_ids.size() OR per_relation < 1 OR per_relation > 8 THEN
    PRINT "invalid_parameters" AS status;
    RETURN;
  END;
  IF visibility_phase < 1 OR visibility_phase > 3 THEN
    PRINT "invalid_visibility_phase" AS status; RETURN;
  END;
  IF scope_id != "" THEN
    ScopeCatalog = {Temporal_Training_Scope.*};
    RequestedScope = SELECT r FROM ScopeCatalog:r WHERE r.scope_id == scope_id AND r.ready;
    IF RequestedScope.size() != 1 THEN PRINT "scope_not_ready" AS status; RETURN; END;
  END;
  FOREACH i IN RANGE[0, @@request_ids.size()-1] DO
    IF @@request_seqs.get(i) == 0 OR @@request_times.get(i) == 0 OR
       (@@request_types.get(i) != "Account" AND @@request_types.get(i) != "Token" AND
        @@request_types.get(i) != "Party" AND @@request_types.get(i) != "Device" AND
        @@request_types.get(i) != "IP" AND @@request_types.get(i) != "Address") THEN
      PRINT "invalid_request" AS status, i AS request_index;
      RETURN;
    END;
    root = to_vertex(@@request_ids.get(i), @@request_types.get(i));
    seed_seq = @@request_seqs.get(i);
    state_seq = seed_seq - 1;
    seed_ts_ms = @@request_times.get(i);
    @@features.clear(); @@distinct.clear(); @@messages.clear(); @@events.clear();
    @@age_encoding.clear(); @@gap_encoding.clear();
    @@out_last = 0; @@in_last = 0; @@invalid = FALSE;
    @@zelle_out.clear(); @@zelle_in.clear();
    @@payment_out.clear(); @@payment_in.clear();
    Roots = {root};
    IF scope_id != "" THEN
      RootScope = SELECT s FROM Roots:s -(Entity_In_Training_Scope>:membership)- Temporal_Training_Scope:r
        WHERE r.scope_id == scope_id AND membership.partition >= 1
          AND membership.partition <= visibility_phase
        ACCUM s.@scope_allowed += TRUE;
    END;
    Visible = SELECT s FROM Roots:s
      WHERE s.getAttr("first_seen_seq", "UINT") <= seed_seq
        AND s.getAttr("first_seen_ts_ms", "UINT") <= seed_ts_ms
        AND (scope_id == "" OR (@@request_types.get(i) != "Account" AND @@request_types.get(i) != "Party") OR s.@scope_allowed);
    IF Visible.size() == 0 THEN
      PRINT "invisible_entity" AS status, i AS request_index;
      RETURN;
    END;
    Metadata = SELECT s FROM Visible:s
      ACCUM @@features += ("age_days" ->
        (seed_ts_ms - s.getAttr("first_seen_ts_ms", "UINT")) / 86400000.0);
    IF @@request_types.get(i) == "Account" THEN
      MetaAccount = SELECT s FROM Visible:s
        ACCUM IF s.getAttr("is_external", "BOOL") THEN @@features += ("is_external" -> 1) END,
          IF s.getAttr("account_type", "STRING") == "deposit" THEN @@features += ("is_deposit" -> 1) END;
    END;
"""
    ]
    for prefix, vtype, pid, rail in [
        ("Transfer", "Zelle_Transfer", "transfer_id", '"zelle"'),
        ("Transaction", "Payment_Transaction", "transaction_id", "t.payment_rail"),
    ]:
        stem = "zelle" if prefix == "Transfer" else "payment"
        for direction in ["out", "in"]:
            if prefix == "Transfer":
                reverse = (
                    "Account_Sent_Zelle_Transfer|Token_Sent_Transfer"
                    if direction == "out"
                    else "Account_Received_Zelle_Transfer|Token_Received_Transfer"
                )
            else:
                reverse = (
                    "Account_Initiated_Transaction|Token_Sent_Transaction"
                    if direction == "out"
                    else "Account_Received_Transaction|Token_Received_Transaction"
                )
            parts.append(f"""    Candidates_{stem}_{direction} = SELECT t FROM Visible:s -(({reverse.replace("|", ">|")}>):e)- {vtype}:t
          WHERE t.event_seq < seed_seq AND t.event_ts_ms <= seed_ts_ms;\n""")
            parts.append(
                scope_events(f"Candidates_{stem}_{direction}", prefix, f"{stem}_{direction}")
            )
            parts.append(f'''    Events_{stem}_{direction} = SELECT t FROM Visible:s -(({reverse.replace("|", ">|")}>):e)- {vtype}:t
          WHERE t.event_seq < seed_seq AND t.event_ts_ms <= seed_ts_ms
            AND NOT t.@scope_blocked
            ACCUM @@invalid += (e.event_seq != t.event_seq OR e.event_ts_ms != t.event_ts_ms
              OR t.event_seq == 0 OR t.event_ts_ms == 0 OR t.amount < 0
              OR (NOT t.amount_present AND t.amount != 0) OR t.currency != "USD"),
            @@{stem}_{direction} += EventRow(t.event_seq, t.event_ts_ms, t.{pid}, "{vtype}",
                   "{stem}_{direction}", {rail}, t.amount, t.amount_present),
            @@{direction}_last += t.event_ts_ms''')
            for name, ms in WINDOWS.items():
                parts.append(f''',
            IF seed_ts_ms - t.event_ts_ms < {ms} THEN
              @@features += ("{name}_{direction}_count" -> 1),
              @@features += ("{name}_{direction}_amount" -> t.amount),
              IF NOT t.amount_present THEN @@features += ("{name}_{direction}_missing" -> 1) END,
              @@features += ("{name}_{direction}_zelle" -> {1 if stem == "zelle" else 0})
            END''')
            parts.append(";\n")
            # Exact unique observed counterparties; tokens are fallback only when no Account role exists.
            role = "To" if direction == "out" else "From"
            for typ, idattr in [("Account", "id"), ("Token", "token_id")]:
                fallback = (
                    f' AND t.outdegree("{prefix}_{role}_Account") == 0' if typ == "Token" else ""
                )
                parts.append(f"""    Unique_{stem}_{direction}_{typ} = SELECT t FROM Events_{stem}_{direction}:t -({prefix}_{role}_{typ}>:e)- {typ}:p
          WHERE e.event_seq == t.event_seq AND e.event_ts_ms == t.event_ts_ms{fallback}
          ACCUM""")
                parts.append(
                    ",\n".join(
                        f''' IF seed_ts_ms - t.event_ts_ms < {ms} THEN
            @@distinct += ("{name}_{direction}_unique" -> "{typ}:" + p.{idattr}) END'''
                        for name, ms in WINDOWS.items()
                    )
                )
                parts.append(";\n")
            parts.append(f"""    taken = 0;
        WHILE @@{stem}_{direction}.size() > 0 AND taken < per_relation DO
          @@events += @@{stem}_{direction}.pop();
          taken = taken + 1;
        END;
    """)
    parts.append("""    FOREACH (key, peers) IN @@distinct DO
      @@features += (key -> peers.size());
    END;
    IF @@out_last > 0 THEN
      @@features += ("out_recency_days" -> (seed_ts_ms - @@out_last) / 86400000.0);
      @@features += ("out_recency_present" -> 1);
    END;
    IF @@in_last > 0 THEN
      @@features += ("in_recency_days" -> (seed_ts_ms - @@in_last) / 86400000.0);
      @@features += ("in_recency_present" -> 1);
    END;
""")
    for window in AMOUNT_RATIO_WINDOWS:
        parts.append(f'''    incoming_amount = 0.0; outgoing_amount = 0.0;
    IF @@features.containsKey("{window}_in_amount") THEN
      incoming_amount = @@features.get("{window}_in_amount");
    END;
    IF @@features.containsKey("{window}_out_amount") THEN
      outgoing_amount = @@features.get("{window}_out_amount");
    END;
    IF incoming_amount < {AMOUNT_RATIO_FLOOR} THEN incoming_amount = {AMOUNT_RATIO_FLOOR}; END;
    amount_ratio = outgoing_amount / incoming_amount;
    IF amount_ratio > {AMOUNT_RATIO_CAP} THEN amount_ratio = {AMOUNT_RATIO_CAP}; END;
    @@features += ("{window}_out_in_amount_ratio" -> amount_ratio);
''')
    TARGETS = (
        ("Account", "Party"),
        ("Token", "Party"),
        ("Account", "Token"),
        ("Device", "Party"),
        ("Device", "Account"),
        ("IP", "Party"),
        ("Address", "Party"),
    )
    for pair, targets in zip(ASSOCIATIONS, TARGETS, strict=True):
        for rel, typ in zip(pair, targets, strict=True):
            pk = {"Token": "token_id", "Address": "address_id"}.get(typ, "id")
            ext = "t.is_external" if typ == "Account" else "FALSE"
            dep = '(t.account_type == "deposit")' if typ == "Account" else "FALSE"
            parts.append(f"""    CandidateAssoc_{rel} = SELECT t FROM Visible:s -({rel}>:e)- {typ}:t
              WHERE e.valid_from_seq <= state_seq
                AND t.first_seen_seq <= state_seq AND t.first_seen_ts_ms <= seed_ts_ms;\n""")
            if typ in ("Account", "Party"):
                parts.append(scope_entities(f"CandidateAssoc_{rel}", rel))
            scope_filter = (
                'AND (scope_id == "" OR t.@scope_allowed)' if typ in ("Account", "Party") else ""
            )
            parts.append(f'''    @@association.clear(); @@associations.clear();
        Assoc_{rel} = SELECT t FROM Visible:s -({rel}>:e)- {typ}:t
          WHERE e.valid_from_seq <= state_seq
            AND t.first_seen_seq <= state_seq AND t.first_seen_ts_ms <= seed_ts_ms
            {scope_filter}
          ACCUM IF e.valid_to_seq == 0 OR state_seq < e.valid_to_seq THEN
            @@features += ("{rel}_active" -> 1),
            @@association += AssociationRow(e.valid_from_seq, t.{pk}, t.first_seen_ts_ms, {ext}, {dep})
          ELSE @@features += ("{rel}_ended" -> 1) END;
        taken = 0;
        WHILE @@association.size() > 0 AND taken < per_relation DO
          @@associations += @@association.pop();
          taken = taken + 1;
        END;
        FOREACH entry IN @@associations DO
          @@messages += MessageRow("{typ}", entry.node_id, "{rel}", "unknown", "", seed_seq,
            seed_ts_ms, 0.0, FALSE, 0, 0, FALSE, 0, 0, 0, entry.first_ms, entry.external, entry.deposit);
        END;
    ''')
    parts.append("""    IF @@invalid THEN
      PRINT "invalid_payment_fields_or_currency" AS status, i AS request_index;
      RETURN;
    END;
    FOREACH item IN @@events DO
      event_vertex = to_vertex(item.event_id, item.event_type);
      Event = {event_vertex};
      @@sender_count = 0; @@recipient_count = 0; @@token_count = 0;
      @@sender_id = ""; @@recipient_id = ""; @@token_id = "";
      @@sender_vertices.clear(); @@invalid = FALSE;
""")
    for prefix, vtype in [("Transfer", "Zelle_Transfer"), ("Transaction", "Payment_Transaction")]:
        parts.append(f'      IF item.event_type == "{vtype}" THEN\n')
        for role, typ, counter, idacc, idattr in [
            ("From", "Account", "sender_count", "sender_id", "id"),
            ("To", "Account", "recipient_count", "recipient_id", "id"),
            ("To", "Token", "token_count", "token_id", "token_id"),
        ]:
            extra = ", @@sender_vertices += a" if role == "From" else ""
            parts.append(f"""        Role_{prefix}_{role}_{typ} = SELECT a FROM Event:t -({prefix}_{role}_{typ}>:e)- {typ}:a
              ACCUM @@{counter} += 1, @@{idacc} += a.{idattr}{extra},
                @@invalid += (e.event_seq != item.seq OR e.event_ts_ms != item.ts
                  OR a.first_seen_seq > item.seq OR a.first_seen_ts_ms > item.ts);
    """)
        parts.append("      END;\n")
    parts.append("""      IF @@invalid OR @@sender_count != 1 OR @@recipient_count > 1 OR @@token_count > 1
         OR (@@recipient_count == 0 AND @@token_count == 0) THEN
        PRINT "invalid_event_roles" AS status, i AS request_index;
        RETURN;
      END;
      recipient_type = "Account"; recipient_id = @@recipient_id;
      IF @@recipient_count == 0 THEN recipient_type = "Token"; recipient_id = @@token_id; END;
      peer_type = recipient_type; peer_id = recipient_id;
      IF item.relation == "zelle_in" OR item.relation == "payment_in" THEN
        peer_type = "Account"; peer_id = @@sender_id;
      END;
      @@previous_ts = 0; @@previous_seq = 0;
      @@pair_1h = 0; @@pair_1d = 0; @@pair_7d = 0;
      Senders = {@@sender_vertices};
""")
    for prefix, vtype, rev in [
        ("Transfer", "Zelle_Transfer", "Account_Sent_Zelle_Transfer"),
        ("Transaction", "Payment_Transaction", "Account_Initiated_Transaction"),
    ]:
        railfilter = " AND t.payment_rail == item.rail" if prefix == "Transaction" else ""
        parts.append(f'''      IF item.event_type == "{vtype}" THEN
            PriorCandidates = SELECT t FROM Senders:s -({rev}>:e)- {vtype}:t
              WHERE t.event_seq < item.seq AND t.event_ts_ms <= item.ts
                AND e.event_seq == t.event_seq AND e.event_ts_ms == t.event_ts_ms{railfilter};
    ''')
        parts.append(scope_events("PriorCandidates", prefix, "prior_" + prefix))
        parts.append("    Prior = SELECT t FROM PriorCandidates:t WHERE NOT t.@scope_blocked;\n")
        for typ, idattr in [("Account", "id"), ("Token", "token_id")]:
            fallback = f' AND t.outdegree("{prefix}_To_Account") == 0' if typ == "Token" else ""
            parts.append(f'''        IF recipient_type == "{typ}" THEN
              Pair_{prefix}_{typ} = SELECT t FROM Prior:t -({prefix}_To_{typ}>:e)- {typ}:a
                WHERE a.{idattr} == recipient_id{fallback}
                  AND e.event_seq == t.event_seq AND e.event_ts_ms == t.event_ts_ms
                ACCUM @@previous_ts += t.event_ts_ms, @@previous_seq += t.event_seq,
                  IF item.ts - t.event_ts_ms < 3600000 THEN @@pair_1h += 1 END,
                  IF item.ts - t.event_ts_ms < 86400000 THEN @@pair_1d += 1 END,
                  IF item.ts - t.event_ts_ms < 604800000 THEN @@pair_7d += 1 END;
            END;
    ''')
        parts.append("      END;\n")
    parts.append("""      gap_ms = 0;
      age_ms = seed_ts_ms - item.ts;
      event_key = item.relation + ":" + item.event_id;
      @@age_encoding += (event_key -> temporal_fourier64_values(age_ms));
      IF @@previous_seq > 0 THEN
        gap_ms = item.ts - @@previous_ts;
        @@gap_encoding += (event_key -> temporal_fourier64_values(gap_ms));
      END;
      @@peer_first_ms = 0; @@peer_external = FALSE; @@peer_deposit = FALSE;
      peer_vertex = to_vertex(peer_id, peer_type);
      Peer = {peer_vertex};
      PeerMeta = SELECT p FROM Peer:p
        ACCUM @@peer_first_ms += p.getAttr("first_seen_ts_ms", "UINT");
      IF peer_type == "Account" THEN
        PeerAccount = SELECT p FROM Peer:p
          ACCUM @@peer_external += p.getAttr("is_external", "BOOL"),
            @@peer_deposit += (p.getAttr("account_type", "STRING") == "deposit");
      END;
      @@messages += MessageRow(peer_type, peer_id, item.relation, item.rail,
        item.event_id, item.seq, item.ts,
        item.amount, item.amount_present,
        age_ms, gap_ms, @@previous_seq > 0, @@pair_1h, @@pair_1d, @@pair_7d,
        @@peer_first_ms, @@peer_external, @@peer_deposit);
    END;
    PRINT "ok" AS status, i AS request_index,
      @@request_types.get(i) AS node_type, @@request_ids.get(i) AS node_id,
      seed_seq AS cutoff_seq, seed_ts_ms AS cutoff_ms,
      scope_id AS scope_id, visibility_phase AS visibility_phase,
      "log1p_s_400d_32x_sincos_v1" AS basis_id,
      @@features AS features, @@messages AS messages,
      @@age_encoding AS age_encoding, @@gap_encoding AS gap_encoding;
  END;
}
""")
    return "\n".join(line.rstrip() for line in "".join(parts).splitlines()) + "\n"
