"""Regenerate the context queries after editing their shared contracts.

gsql/queries/training_context.gsql and gsql/analytics/analytics_context.gsql are
generated by tigergraph.render. A changed query needs a new contract (the value
contract.server holds for it, CONTEXT_CONTRACT or ANALYTICS_CONTRACT, derived from
the rendered text); the script names the value to set and exits 1 until it is set.
"""

import argparse
from collections.abc import Callable
import sys

from mule_pattern_learner.contract.server import (
    ANALYTICS_CONTEXT_FILE,
    ANALYTICS_CONTRACT,
    CONTEXT_CONTRACT,
    CONTEXT_QUERY_FILE,
)
from mule_pattern_learner.paths import GSQL_DIR
from mule_pattern_learner.tigergraph.render import (
    analytics_contract,
    context_contract,
    render_analytics_query,
    render_context_query,
)

# Each generated file: its renderer, the contract constant's name and value, and the
# contract its text derives.
QUERIES: dict[str, tuple[Callable[[], str], str, str, Callable[[], str]]] = {
    CONTEXT_QUERY_FILE: (
        render_context_query,
        "CONTEXT_CONTRACT",
        CONTEXT_CONTRACT,
        context_contract,
    ),
    ANALYTICS_CONTEXT_FILE: (
        render_analytics_query,
        "ANALYTICS_CONTRACT",
        ANALYTICS_CONTRACT,
        analytics_contract,
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only compare the rendered texts with the files; exit 1 when one differs",
    )
    args = parser.parse_args()
    status = 0
    for name, (render, constant, recorded, derive) in QUERIES.items():
        path = GSQL_DIR / name
        contract = derive()
        if contract != recorded:
            print(f"set contract.server.{constant} = {contract!r}, then render again")
            status = 1
            continue
        text = render()
        if args.check:
            same = path.read_text() == text
            print(f"{path.name} {'matches' if same else 'differs from'} the generator")
            status = status if same else 1
        else:
            path.write_text(text)
    return status


if __name__ == "__main__":
    sys.exit(main())
